Header search box
CauchyE/telescope pull request #236
Opened 2021-12-09 14:05 UTC by taro04

[https://github.com/lcnem/telescope/issues/213](https://github.com/lcnem/telescope/issues/213)、[https://github.com/lcnem/telescope/issues/214](https://github.com/lcnem/telescope/issues/214)
に対する修正です。

＞＞txs=tx_hash や accounts=address で検索バーに入力されてしまうのは違和感（=に読み替えました。）
＞＞検索アイコンが検索の実行ではなく、検索バーをアクティブにするボタンになっているのが直感的でない
　現状一つの検索バーでアドレスと、トランザクションを扱っているので仕方ないかなと思っています。
　（検索ボタンを押した際に自動判定などはありかもしれないですが。）

＞＞検索後、再度検索バーをクリックするとクエリ文字列が二重で入力されてしまう
　一度検索すると、例えば”address=hoge”が検索バーに残り、それをまた検索”address=address=hoge”というように、
　無限にaddress=が増えていくようになっていたので入力文字列に=があるかを判定するようにしました。

＞＞未入力状態で検索アイコンが黒くなっているのが見づらい
　requiredが設定されていましたが、検索バーは入力必須ではないので削除しました。
　結果常時白のアイコンになりました。

＞＞[All/Search] アドレスやトランザクションハッシュを入力した時にすべて表示されず見切れてしまう #214
　こちらご相談なのですが、そもそもすべて表示させる必要はあるでしょうか？
　モバイル表示などは表示しても確実に見切れると思います。

またnotionのタスク「サイドナビ展開用のボタンが非表示ではなく、インビジブルになっているだけ」の件合わせて修正しました。
ご確認お願い致します。

2021-12-09 14:13 UTC, taro04 commented on projects/main/src/app/views/toolbar/toolbar.component.html
> +  <mat-form-field appearance="fill" (submit)="onSubmit(searchValueRef.value)" [style.width.%]="300">
tailwindの表記（class=”w-full”）では動作しなかったため、CSSを直接書いています。
100%=244pxで固定になっていてページサイズに合わせ動的に変化させることができませんでした。
（ページサイズではないものに対象を合わせている？）
何か分かりましたらご教示いただきたくお願いします。

2021-12-10 06:08 UTC, YasunoriMATSUOKA requested changes
質問への回答や、現時点のコードについて感じたことをコメントしました。
ご参照ください。

2021-12-10 06:08 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/toolbar/toolbar.component.ts
> +      },
ここについては、今の進め方だと、かなり記述量増える＆実装意図が見えにくい形のごり押しに感じられて、ちょっと心配です。仕様も含めて、改めて整理して見直した後、実装したほうが良いかなと感じています。

文字数等のバリデーションを行った上で、以下をAPIたたいて判定し、該当するものがあれば、それを選択肢として表示するような形にこの機会に修正するのが良いのではないかと思いました。(時間かかってもよいので、チャレンジしてみてください。)

その際、もし行けそうなら、単純な数値で、なおかつLatestBlockHeight以下の場合、blockについても検索から飛べるようになっていると親切かなあと思ったりもしました。

- そのアドレスが存在するか否か
- そのトランザクションハッシュのトランザクションが存在するか否か

バリデーションやAPIのリクエスト結果がNGだった場合は、一旦は何もしない形で検討してみてください。

なおその際、フォームの見た目についても、インプットされた値がそのまま表示される形で問題なく、
有効な値の場合に下に表示される選択肢だけ、AddressなのかTxHashなのかわかるようになっていればOKかなと思いました。

各コンポーネント間のイベントによる情報のやり取り等を改めて整理して、実装にチャレンジしてみてください。

時間かかってもよいので、この機会に根本的に修正を試みてみましょう。

別のプルリクに分けてもよいので、そのあたりの匙加減はお任せします。

別のプルリクに分ける場合は、ここの変更はいったんもとに戻しておくのが良いかなと思いました。

2021-12-10 11:48 UTC, taro04 commented on projects/main/src/app/views/app.component.html
> +      <ng-container *ngIf="drawerClosed$ | async">
全体を（）でくくればよかったんですね。こちら思い付きはしたんですが、意図した動作せず、（変数名分かりやすいほうが良いかなという思いもあって、）drawerClosedを作りました。修正します。

2021-12-10 12:02 UTC, taro04 commented on projects/main/src/app/views/toolbar/toolbar.component.ts
> +      },
承知しました。こちらは別のプルリクで実装します！

2021-12-14 08:35 UTC, YasunoriMATSUOKA approved these changes
LGTM!
![LGTM](https://image.lgtmoon.dev/84631)
プロジェクト名のリブランディングにあわせて、レポジトリ等大幅に変更していて、マージできるまでお待たせしてすみません。
これでOKだと思うのでこちらでマージしておきます。

2021-12-14 08:41 UTC, merged