feat: deal with transaction that has some space characters
CauchyE/telescope pull request #247
Opened 2021-12-27 11:57 UTC by taro04

[https://github.com/CauchyE/telescope/issues/245](https://github.com/CauchyE/telescope/issues/245)
のISSUE修正です。

以下参考に実装しました。
[https://www.nishishi.com/javascript-tips/trim-space-chars.html](https://www.nishishi.com/javascript-tips/trim-space-chars.html)

ローカル環境での動作確認と、コンソールへの出力で確認しました。
![image](https://user-images.githubusercontent.com/75844498/147469613-73f3c4f7-909b-4deb-a59f-b67b98006983.png)
コンソール出力結果
![image](https://user-images.githubusercontent.com/75844498/147469405-dcdae40b-8364-415e-b57a-b38a78114a22.png)

ご確認お願い致します。

2021-12-27 12:32 UTC, taro04 commented
・privateKeyも同様に空白を１字と認識しています。UXを考えると個人的に同様の修正をした方が良いと思いますがいかがでしょう。

2021-12-27 12:40 UTC, YasunoriMATSUOKA commented
お願いします。Issueも立てておいてもらってよいでしょうか？
https://github.com/CauchyE/telescope/pull/247#issuecomment-1001547924

2021-12-27 12:43 UTC, YasunoriMATSUOKA requested changes
@taro04 
このプルリクざっとレビューしたのですが、varは避けて最低限letにしましょう。(本当はletも避けてconstにできるだけすべきですが、ここでは若干妥協してletを使っているという感じです。ただ、あえてvarを使う必要はないと思うので、最低限letにしましょう。)

2021-12-27 13:09 UTC, taro04 commented
@YasunoriMATSUOKA 
確認ありがとうございます。varとletの違いを知れてよかったです。constで支障ないのでconstで定義しました。

2021-12-28 04:45 UTC, YasunoriMATSUOKA commented
@KimuraYu45z 
application service内で変換的な処理を行うべきか、service内で変換的な処理を行うべきか若干迷いがあります。
現時点ではapplication service内でアドレスに含まれる空白文字を除く処理を入れているのですが、いかがでしょうか？
一応念のため確認させてください。

2021-12-28 04:49 UTC, YasunoriMATSUOKA commented
Issueに書いた期待値自体が微妙だったかもと感じ始めました。
Formのバリデーションでチェックできる内容な気がしはじめていて、ちょっと改めて考えてみたほうが良いかもと思い始めています。

2021-12-28 05:45 UTC, taro04 commented
@YasunoriMATSUOKA cc: @KimuraYu45z 
確かにバリデーションで制限する内容かもしれないですね。ただユーザーが意図して空白を入れるケースって少ないと思うので、バリデーションでチェックして通さないとユーザーが気づいていない空白を探す労力を強いるのかなとも思います。

2021-12-28 05:48 UTC, KimuraYu45z commented
onblurにてスペース消すっていう方法もなくはないですね
ちょっとユーザーからすれば怖い挙動かもしれないけど

2021-12-28 05:59 UTC, yutaro-elk commented
横から失礼します。
文頭文末に空白があるか否かはユーザーが直さなくてもシステム側で変換できるものなので、バリデーション時に弾かないほうが良いかと思います。
住所入力で全角文字の入力が必要であっても、ユーザー側にやらせるんではなくシステム側で吸収するイメージです。

2021-12-28 06:21 UTC, YasunoriMATSUOKA commented
色々アドバイスありがとうございます。
serviceにて、シンプルにWhitespaceを取り除く形で進めようと思います。

2021-12-28 07:05 UTC, YasunoriMATSUOKA approved these changes
実装、アドバイス、ありがとうございました！
LGTM!
![LGTM](https://image.lgtmoon.dev/151695)

2021-12-28 07:05 UTC, merged