feat: remove unintentional whitespace in private key
CauchyE/telescope pull request #256
Opened 2022-01-07 15:20 UTC by taro04

[https://github.com/CauchyE/telescope/issues/248](https://github.com/CauchyE/telescope/issues/248)の修正です。

bank/send で秘密鍵を入力する際に、空白文字を切るように、以下と同様に修正しました。
[https://github.com/CauchyE/telescope/pull/247](https://github.com/CauchyE/telescope/pull/247)

ローカルで秘密鍵の前後にスペースを付加して動作確認しました。ご確認お願い致します。

2022-01-12 09:53 UTC, YasunoriMATSUOKA commented
@KimuraYu45z 
この件、後々展開していくときのために事前に統一しておきたく、アドバイスください。

最終的にサービスで使う値が以下のような流れで渡されていくのですが、対象の値が最終的なServiceで使用される際に問題のない形になっているよう変換する処理を加える場合、どこにその処理を書くのが適切でしょうか？
ViewComponent -> PageComponent -> ApplicationService -> Service

@YasunoriMATSUOKA の意見はServiceに書くのが(一番重複が少ないので)自然かな？と思って、アドレスに関するこの件と同様の修正では、Serviceの中でその処理を書いていた( https://github.com/CauchyE/telescope/pull/247/commits/523dfd1b1b137b30b99bc14119043f948facd302 )のですが、

今回 @taro04 にて実装頂いたこのプルリクの現状は、ApplicationServiceの中に書いてもらっている感じになっていて、

どこで書くのが望ましいでしょうか？

データの流れの起点にするか、データが最後にたどり着くサービスにするか、どちらかかなあくらいに自分としては思っていたのですが、他のトランザクションにも展開していくことを思うと、最初に統一的に決めておいたほうが良いと思っていて、木村さんの所感を伺いたく思います。

お手数ですがよろしくお願いします。

2022-01-17 09:51 UTC, KimuraYu45z commented
あーそうかたしかに変換処理入れる場所に悩みますね、、、

空白詰めはapplicationじゃないserviceに仕込みましょうか。それ以外のところに入れるのはしっくりこないですね

uint8arrayに関しては、view componentのevent emitの直前に入れても良いかもしれないですね。型変換のみは良いような気がします。

2022-01-17 10:21 UTC, YasunoriMATSUOKA requested changes
@taro04 cc: @KimuraYu45z 
この処理はapplication.serviceに書くのではなく、serviceに書く形で以降の実装を統一して進めましょう。
経緯や理由については以下コメントのやり取りを参考にしてください。
https://github.com/CauchyE/telescope/pull/256#issuecomment-1010857368
https://github.com/CauchyE/telescope/pull/256#issuecomment-1014332112

なお、秘密鍵をstringではなくUInt8Arrayで持つように変更するというIssueも新たに出ていますが、それは、このプルリクとは別で対応するようにしたほうが混乱が無いかなと思ったので、一旦変更内容は現状のプルリクの内容でOKで、bank.application.service.ts ではなく bank.service.ts を修正する形に修正お願いします。
https://github.com/CauchyE/telescope/issues/260

2022-01-17 11:55 UTC, taro04 commented
実装箇所をbank.app.service.tsからbank.service.tsに修正し、ローカルで動作確認しました。（すみませんtoAddressもbank.service.tsでした。）
ご確認お願い致します。

2022-01-17 12:36 UTC, YasunoriMATSUOKA approved these changes
![LGTM](https://image.lgtmoon.dev/5820)

2022-01-17 12:46 UTC, merged