Hotfix/pagination query
CauchyE/telescope pull request #258
Opened 2022-01-13 13:14 UTC by taro04

引き続き動作確認はできていないのですが、確認のためPR作成します。

2022-01-13 13:39 UTC, taro04 commented on projects/main/src/app/pages/blocks/blocks.component.ts
>          [...Array(pageSize).keys()].map((index) => {
98行目のConsole.logで確認するとpageSizeに1は入っていませんが、latestBlocksが１つしか表示されない状況でした。
98行目のConsole.logで確認した際に、出力がnumber（’’やnなどの修飾無し）だったこと、そもそもBehaiverSubject<number>型であるpageSize$に入力できている時点でnumberであることは自明だかと思っていたのですが、試しに`pageSize*1`の表記にしたら指定したページサイズ分のブロックが表示されるようになりました。

2022-01-14 14:17 UTC, taro04 commented
実装完了しました。

・ページネーションの操作をBehaiverSubjectでなくクエリパラメータとして保持しました。
・（subscriptionを使わずに）Observableのみでプロパティが更新されるようにしました。

ローカルで動作確認しました。ご確認お願い致します。

https://user-images.githubusercontent.com/75844498/149529088-fe7c9f34-1ddb-4d62-8d1d-7eee63297697.mp4

2022-01-17 11:10 UTC, YasunoriMATSUOKA requested changes
@taro04 cc: @KimuraYu45z 
全体的な修正方針は大変すばらしいのですが、query parameterが無かった場合や、素直にNumberに変換できない場合バグってしまう実装になっていると思います。

ソースコードにレビューコメントつけたので、修正お願いします。

2022-01-17 11:10 UTC, YasunoriMATSUOKA commented on projects/main/src/app/pages/blocks/blocks.component.ts
> +    this.pageNumber$ = this.route.queryParams.pipe(map((params) => Number(params.pages)));
query parameterが無いパターンや、素直にNumberに変換できないようなパターンもエラーなく実行できるよう修正お願いします。

2022-01-17 11:10 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/app.component.html
> +      <mat-list-item routerLink="/blocks" [queryParams]="{ perPage: '10', pages: '1' }">
デフォルトでは、 http://locaohost:4200/blocks に遷移させ、その状態でもデフォルト的なページネーションで、最新ブロックからのブロック一覧が確認できるように実装しましょう。

2022-01-17 13:33 UTC, taro04 commented
以下のエラー処理を追加しました。
・pageNumberが数字かどうかかつ、存在するページ以下か確認。
・最終ページでページサイズに満たない表示の場合の処理

以下の条件で適切に表示されることを確認しました。
・クエリパラメータなし。
・クエリパラメータに文字を入力。
・クエリパラメータに大きすぎるページを入力（例：200ページしかないのに220ページ）
・最終ページに半端な一部のみ表示。
ご確認お願い致します。

2022-01-18 06:18 UTC, YasunoriMATSUOKA requested changes
@taro04 
動作としては問題解決されたと思います。ありがとうございました。後は、以下プルリクのような修正を追加で加えると理想的かなと思いました。確認の上、問題無ければマージして、もし追加で修正するべきところ等あれば、修正頂けると助かります。よろしくお願いします。
https://github.com/CauchyE/telescope/pull/266

2022-01-18 11:56 UTC, taro04 commented
修正ありがとうございます。
ご指摘いただいた点今後の実装で意識します。（マジックナンバーを使わない／undefinedは謎の定数を代入せずに素直にundefinedとして扱う。）

デバックについて昨日同様以下の条件で適切に表示されることを確認しました。
・クエリパラメータなし。
・クエリパラメータに文字を入力。
・クエリパラメータに大きすぎるページを入力。
・最終ページにページサイズに満たないブロック一覧が表示。

ご確認お願い致します。

2022-01-19 06:19 UTC, next-web-technology-admin approved these changes
![LGTM](https://image.lgtmoon.dev/120622)

2022-01-19 06:20 UTC, YasunoriMATSUOKA approved these changes
![LGTM](https://image.lgtmoon.dev/120622)

2022-01-19 06:45 UTC, merged