fix: add max token varidation to input form
CauchyE/telescope pull request #270
Opened 2022-01-20 14:11 UTC by taro04

[https://github.com/CauchyE/telescope/issues/262](https://github.com/CauchyE/telescope/issues/262)の修正です。

ngFormのinputに[max]を追加する方向で実装進めています。
[max]がstring｜numberしか受け付けないので意外と難しいと感じています。

試したこと
・`"coins[i].amount as string"`　⇒　html内で`as string`が使えない。
・/page側でObservable<string[]>作る。　⇒　`|async`でview側に渡す時点で`|null`がつく。

ごり押し感がありますが、/view側コンポーネントに`maxAmount: string[]`を定義して、
for文でcoins?からamountを取り出すしかないかと思っています。

実装の方針について、良い方法ありましたらコメントいただけると幸いです。

2022-01-20 14:59 UTC, KimuraYu45z commented
自分なら

 || 0
ですかね。

2022-01-21 07:45 UTC, YasunoriMATSUOKA commented
@taro04 
大きな方針として以下を考慮してみてください。

- simulateの際にはdummyの手数料として1uguu消費する設定でトランザクションデータを生成していると思うので、その1uguuを考慮して残高が足りる or 足りないを判定するようにする必要があるかも？という気がしました。この点、考慮に入れてあげてください。(特にそれでエラーになっていないようだったらすみません。)
- 型はもっとすなおに書いて良いのではないかという気がしました。(文字列型に変換する必要があるなら、`num.toString()`みたいにすればいいのかなというところと、undefinedでありうるならそこの部分を木村さんからのコメントを参考に処理すると良いと思います。)
- 配列的な値は複数形になっているとソースコードの可読性があがるのでそうしておくのが良いと思います。
- なお手数料については、simulateの1uguuではなく、simulate結果から推測される手数料で最終的に残高足りる or 足りないを判断してあげられるとより良いと思っています。これは別のプルリクでもよいと思います。Issue残した上で頭の片隅に認識入れておいてもらえると助かります。

2022-01-21 12:09 UTC, taro04 commented
`[max]="coins && coins[i].amount || 0"`で行けました！
二項演算子を二回使うとは。勉強になりました。

次に松岡さんのコメントの通り、
１）uguuを最大値 入力すると、simulatitonが通らない。
２）uguuを最大値-1 入力すると、simulationは通るがその後のtx送信は失敗。
３）uguuを最大値-手数料分 入力すると、simulationもtx送信も成功。
の状況です。

１）についてはuguuだけはsimulationを通すために`coins[i],amount - 1 `しなくてはならず、
　やはりコンポーネントに`maxAmounts: number[]`を持たせる必要があるかと思っています。
　（html内でstring型をnumber型に変更できる方法があればご教示いただきたいです。）

２）はエラーメッセージが出るので残高が残高が足りないことは伝わりますが、
　無駄に手数料払ってtx送信することになるので、止めてあげた方が親切かなと思いました。
　別プルリクで対応します。
 
![image](https://user-images.githubusercontent.com/75844498/150523544-84f23d8d-5998-4632-ae7c-a48fefc443db.png)

2022-01-21 13:08 UTC, taro04 commented
各コインの所持枚数でバリデーション（ただしuguuは-所持枚数-1）を設定しました。
ローカルで以下の通り、所持枚数以上の数値を入力できないことを確認しました。

![image](https://user-images.githubusercontent.com/75844498/150531980-9edc86e1-0844-445f-8dc5-3b573b342aa9.png)

ご確認お願い致します。

2022-01-28 05:52 UTC, YasunoriMATSUOKA approved these changes
@taro04 
レビュー遅くなってすみません。
修正したほうが良いと思う点をソースコードにコメントしました。
確認と修正をお願いします。

2022-01-28 05:52 UTC, YasunoriMATSUOKA commented on projects/main/src/app/pages/cosmos/bank/send/send.component.ts
> +          if (coins[index].denom === 'uguu') {
@taro04 
uguuをハードコードして判定するのではなく、minimumGasPricesに含まれているdenomなら、マイナス1するような形の判定に修正すべきかなと思いました。

2022-01-28 05:52 UTC, YasunoriMATSUOKA commented on projects/main/src/app/pages/cosmos/bank/send/send.component.ts
> +        return [...coins.keys()].map((index) => {
@taro04 
無理に`[...coins.keys()].map((index) => {`のようにせずとも、`coins.map((coin, index) => {})`のようにindexを取って使えるので、そのように実装したほうが自然で情報を失わずに済んで可読性の高い実装になって良いように見えました。

2022-01-28 05:52 UTC, YasunoriMATSUOKA commented on projects/main/src/app/pages/cosmos/bank/send/send.component.ts
> +          let eachAmount = parseInt((coins && coins[index].amount) || '0');
@taro04 
letを使わず、一旦一つのmapで型変換を行い、次にもう一つのmapでマイナス1すべきかどうかチェックしてマイナス1するように実装したほうが自然かつ堅牢かなと思いました。

全体的には以下のようなイメージです。

```
map((coin, index) => {
  // convert type from string to number
  // in this point, keep denom
  return numberdCoin;
}).map((numberdCoin, index) => {
  // check and if need minus 1
  return finalCoin;
})
```

2022-01-28 10:11 UTC, YasunoriMATSUOKA requested changes
間違えてApproveしてしまっていました。コメントを参考に修正お願いします。

2022-02-01 05:16 UTC, YasunoriMATSUOKA requested changes
@taro04 
すみません。お願いしていた修正方針が良くなかったように感じていて、改めてソースコード内のコメントを参考に修正方針再検討してもらえないでしょうか？
お手数おかけしてすみませんがよろしくお願いします。

2022-02-01 13:14 UTC, taro04 commented on projects/main/src/app/pages/cosmos/bank/send/send.component.ts
> +            });
承知しました。javaでArray標準のメソッドはいろいろと便利なものがあるのですね。
`for`は違うよなと思って、無理やり`map`使っていましたが、まさに`.some()`が探していたものでした。
教えていただきありがとうございます。

2022-02-01 14:28 UTC, taro04 commented
ご確認ありがとうございます。
・viewで選択されたgasDenomを-1すべきの点はその通りだと思います。
　⇒ 修正しました。

現状送信の際の挙動は以下の３パターンです。
１）uguuを最大値 入力すると、simulatitonが通らない。
　　（「Send」を押すとエラー）
２）uguuを最大値-1 入力すると、simulationは通るがその後のtx送信は失敗。
　　（「Send」を押すと、confirmDialogが出る。dialogの「OK」押すとエラー）
３）uguuを最大値-手数料分 入力すると、simulationもtx送信も成功。

このPRでは１）をケアするために最大値-1をバリデーションに設定します。
別PRで2をケアするためにconfirmDialogの改造を行います。

そもそもsimulationに”1”を設定する必要がある確認したところ、
”0”ではsimulationが通らないようです。
![image](https://user-images.githubusercontent.com/75844498/151980169-5894ee22-e91d-42f9-9ad7-2429af402993.png)

と実装しているときは何はともあれsimulationを通さないといけないと思っていたのですが、
改めてコメント見直しPRコメント作成しているうちに、
確かにSimulation分足りないのも、手数料分足りないもの、分ける必要はないなと思いなおしました。（コメントいただいたとおりで申し訳ないです、）

ここまでレビューいただいて恐縮ですが、以下のように修正しなおそうと思いました。

・入力バリデーションは単純に所持数（uguu-1しない）
・uguu（gasDenom）の最大数を「Send」された場合は、その時点でエラーメッセージdialog表示
・手数料が足りない場合、「最大***uguu（gasDenom）まで」とdialog表示
・上記どちらも問題ない場合、現状のconfirmDialog表示

このあたりの挙動について違和感ありましたらご教示いただけると幸いです。

2022-02-02 15:05 UTC, taro04 commented
以下の方針で実装しました。
・入力バリデーションは単純に所持数（uguu-1しない）
・手数料が足りない場合、「見直してくれ」とDialog表示
・上記どちらも問題ない場合、現状のconfirmDialog表示

https://user-images.githubusercontent.com/75844498/152178866-f4a3f047-44ae-422f-b2ad-83fd89848539.mp4

・動作は実現できていると思います。
・ボタンの色や、maxAccountが不要になったのでコードから消すなど、
　明日もろもろ整えようと思います。
・手数料足りないときのメッセージは計算した差分を表示することも考えましたが、
　1.1のマージンを見た値であること、減らしたら減らした分手数料も変化するので
　あえて見直しの指示だけにしました。

2022-02-03 09:52 UTC, YasunoriMATSUOKA requested changes
@taro04 
コメント追記したので参考にしてみてもらえると助かります。

2022-02-03 09:52 UTC, YasunoriMATSUOKA commented on projects/main/src/app/models/cosmos/bank.application.service.ts
> +        const amountForSimulation = parseInt(amount.amount || '0') - 1;
uguuの残高がない場合、amountForSimulationがマイナス1になって、simulationがエラーになりそうに見えました。(uguuのFaucetを回さずubtcだけ残高として保有している状態等で発生すると思います。)

これを避けるためには、ひと手間必要なものの、simulationがエラーにならないamount, coins, minimumGasPricesの組み合わせであることを事前にチェックして、エラーになりそうなら、simulationのAPIを叩く前にはじく必要がありそうかなと思いました。(try catchでキャッチしてエラーメッセージは出るのですが、エラーメッセージがCode400みたいな抽象度の高いものになってしまい、詳細がユーザーにわからない状況になってしまうんですよね...)

例えば、一例としては、以下のようなイメージの実装を追加する感じかなと思いました。(alertのところはmat-dialogやsnackbar等で良い感じに実装頂けると助かります。)

```
    const feeDenom = minimumGasPrice.denom;
    const simulationFeeAmount = 1;
    const tempAmountToSend = amount.find(
      (amount) => amount.denom === minimumGasPrice.denom,
    )?.amount;
    const amountToSend = tempAmountToSend ? parseInt(tempAmountToSend) : 0;
    const tempBalance = coins.find((coin) => coin.denom === minimumGasPrice.denom)?.amount;
    const balance = tempBalance ? parseInt(tempBalance) : 0;

    if (amountToSend + simulationFeeAmount > balance) {
      alert(
        `Insufficient fee margin for simulation!\nAmount to send: ${amountToSend}${feeDenom} + Simulation fee: ${simulationFeeAmount}${feeDenom} > Balance: ${balance}${feeDenom}`,
      );
      return;
    }

```

既に実装頂いた内容と近い処理を重複して書いているような気持ち悪さがある気もするので、もっといい書き方もあると思います。そのあたりは適宜チャレンジしてみて頂けると助かります。

2022-02-03 09:52 UTC, YasunoriMATSUOKA commented on projects/main/src/app/models/cosmos/bank.application.service.ts
> +    });
間違っているわけではなく好みの問題かもしれませんが、空の配列を新たに定義してpushで詰めていくより、元となる配列からmapで生成した結果として一発で定義したほうが自然かなと思いました。

```suggestion
    const fixedAmount: proto.cosmos.base.v1beta1.ICoin[] = amount.map((amount) => {
      //has gas denom
      if (
        maximumGasPrice?.amount === amountGasPrice?.amount &&
        amount.denom === minimumGasPrice.denom
      ) {
        const amountForSimulation = parseInt(amount.amount || '0') - 1;
        return { amount: amountForSimulation.toString(), denom: amount.denom };
      } else {
        return amount;
      }
    });
```

2022-02-03 09:52 UTC, YasunoriMATSUOKA commented on projects/main/src/app/models/cosmos/bank.application.service.ts
>        })
自分自身の好みとしては、ダイアログで警告表示するなら、別のコンポーネントベースのダイアログに分けたほうが色々すっきりするかなという印象です。省エネ的に、他のエラーメッセージと同様に、スナックバーで実装するのもありかなとも思いました。

2022-02-03 09:52 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/cosmos/tx-fee-confirm-dialog/tx-fee-confirm-dialog.component.html
> +  </button>
好みのレベルになる気もしますが、手数料表示とトランザクション実行最終確認と、手数料不足の警告表示(とトランザクション実行止める)のは、ダイアログにするならコンポーネント分けたほうがいいかなと思いました。
(一旦、スナックバーで楽に実装しておくというやり方でもよいかもという気もしています。)

2022-02-03 09:52 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/cosmos/tx-fee-confirm-dialog/tx-fee-confirm-dialog.component.ts
> +      isTxFeeOver: boolean;
好みのレベルになる気もしますが、手数料表示とトランザクション実行最終確認と、手数料不足の警告表示(とトランザクション実行止める)のは、ダイアログにするならコンポーネント分けたほうがいいかなと思いました。
(一旦、スナックバーで楽に実装しておくというやり方でもよいかもという気もしています。)

2022-02-03 09:52 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/cosmos/bank/send/send.component.ts
> +    this.gasPriceSelected.emit(this.selectedGasPrice);
これ、詳細にデバッグできているわけではないのですが、同様の実装を、onMinimumGasAmountSliderChangedに入れる必要はないでしょうか？

スライダーでGas Priceの数値を変更したとき、反映されないような気がしました。
(違ってたらすみません。)

2022-02-03 14:21 UTC, taro04 commented
コメントありがとうございました。
確かにuguuが０のケースはケアできてませんでした。
松岡さんの参考コードでuguuが最大値の場合も０の場合も対応できましたので、ほぼそちらを使用させていただいております。

動作
https://user-images.githubusercontent.com/75844498/152357800-a264dd66-9751-47f8-a20d-080bbbe546f7.mp4

０の場合
![image](https://user-images.githubusercontent.com/75844498/152357760-c0f0a2c1-7704-4488-be39-5ebeff122aa4.png)

ユーザーへの表示について現在スナックバーで実装しています。
ご確認お願いいたします。


なお個人的にはユーザーへの異常操作のアナウンスなどは、今後、以下の理由でアラートに統一しても良いのではと思っています。

・スナックバー：文字が小さい、またユーザーのタイミングで消すことができない
・個別のダイアログ：想定される異常操作ごとにダイアログ作るとコンポーネントが多くなる気がする。ある程度まとめるにしてもどれはまとめるが判断に迷う。

（そもそもアラートはデバック用だ、みたいな経緯がありましたらご容赦ください。）

2022-02-04 09:22 UTC, YasunoriMATSUOKA requested changes
概ねOKなのですが、通知に関する以下コメントを受けて、自分でも再確認してみた結果、スナックバーでユーザー自身で閉じるような実装が可能そうに見えたので、コード中のコメント追記した方法(第二引数に閉じるためのボタンのラベル名を文字列で指定してやることで、ユーザー自身で閉じるまで開きっぱなしにできそう)に統一するのが良いかなと思いました。(自分自身、これまで深堀していなかったところで、把握しておらず、すみません。)

このプルリクでは、bank sendに関する部分だけ、エラー通知のスナックバーはユーザー自身が閉じる形に修正して、それ以外のエラー通知のスナックバーをその形に統一するのは、別のプルリクで改めてやるのはどうでしょう？

ご検討ください。

この修正で最後になると思います。色々たくさん検討してもらって感謝です。

> ・スナックバー：文字が小さい、またユーザーのタイミングで消すことができない
> ・個別のダイアログ：想定される異常操作ごとにダイアログ作るとコンポーネントが多くなる気がする。ある程度まとめるにしてもどれはまとめるが判断に迷う。

2022-02-04 09:22 UTC, YasunoriMATSUOKA commented on projects/main/src/app/models/cosmos/bank.application.service.ts
> +      );
ユーザーが任意のタイミングでスナックバーをクローズできるようにするには以下のように実装すると可能そうな気がしているので、簡易的にアラート的なユーザー通知を行うには、この書き方に統一するのがよいかもしれませんね。(松岡もこれまであまり詳細調べておらず、このような書き方できるのを、今回コメント頂いて調べて初めて把握しました。意見ご提案感謝です。)

```suggestion
      this.snackBar.open(
        `Insufficient fee margin for simulation!\nAmount to send: ${amountToSend}${feeDenom} + Simulation fee: ${simulationFeeAmount}${feeDenom} > Balance: ${balance}${feeDenom}`,
        'Close',
      );
```

エラー通知系は、一旦これに統一する形で、このプルリクでは、bank send系だけまず修正し、別のプルリクで、全体的に統一する修正を加えてあげるのが良いかなと思いました。

成功通知系は、数秒だったら消えるスナックバーの現状の実装でいいかなと思いました。

2022-02-05 11:17 UTC, taro04 commented
ご確認、調査いただきありがとうございます。
closeのボタンの動作を確認しました。
![image](https://user-images.githubusercontent.com/75844498/152639511-e2e05bb2-ba50-43f7-aaa5-2fc21c8c8a6f.png)
（色もアクセントカラーと合っていて良いですね。）

ご確認お願いいたします。

エラー通知系の修正についてイシュー立てておきます。

2022-02-07 07:39 UTC, YasunoriMATSUOKA approved these changes
![LGTM](https://image.lgtmoon.dev/5839)

2022-02-07 08:29 UTC, merged