fix: pagination by query parameter
CauchyE/telescope pull request #271
Opened 2022-01-25 14:35 UTC by taro04

@YasunoriMATSUOKA 
目的のクエリパラメータにページネーション＆TxTypeの情報を持たさせる件は完了しています。

気になる点が、
`this.txs$ = combineLatest([`を
・mergeMapで受けとるか、
・switchMapで受け取るか、
という点です。

・switchMapの場合
Txが無いType（例：auth）を選択するとリストが更新されません。
https://user-images.githubusercontent.com/75844498/150993076-f678cdbc-8d24-4884-aaa9-d32512d68a19.mp4

・mergeMapの場合
Txが無いType（例：auth）を選択すると空のリストが表示されますが、
ページを進めると表示されるリストがページを行ったり来たりします。
https://user-images.githubusercontent.com/75844498/150993512-6696c520-f11d-484b-a99d-b9b8820bc963.mp4

（switchMapで複数回発火して複数回`[]`を返しますが、[]から[]の変更なので、他のコン　　ポーネントには変更があったと通知されない状況？）

これまで通りswitchMapで問題ないか、
もしくはmergeMapにして何か手だてがあるかコメントいただけますと幸いです。

2022-01-28 10:10 UTC, YasunoriMATSUOKA requested changes
@taro04 
デバッグしてみたのですが、現時点では正常に動作していないパターンが普通にあるように見えました。

修正するにあたって、こういう方向性でやってみるとどうかなと思った内容をコメントしましたが、まだ考えるべきことがありそうな気がしています。

この件は、しっかり理解した上で、確実に修正を進めていきましょう。

2022-02-23 07:53 UTC, taro04 commented
@YasunoriMATSUOKA 
確認、コメントありがとうございます。
ご指摘いただいた通り、クエリパラメータが無いときに動作しない実装となっており、修正しました。動作についてコードの方にコメント記載しますので、ご確認いただけると幸いです。

2022-02-23 08:02 UTC, taro04 commented on projects/main/src/app/pages/txs/txs.component.ts
> +    );
>ここのswitchMapをmergeMapやmapに変えてみてはどうでしょう？

アイデアありがとうございます。
が、動き変わりませんでした。

2022-02-23 08:10 UTC, taro04 commented on projects/main/src/app/pages/txs/txs.component.ts
> +        console.log("error2")
this.txs$ のオペレータについてtxTypeをbankからauthに変えて、エラーになったときに、
 
・switchMapだと、158行のerror1までしかコンソールに表示されません。
・mergeMapだと、158行のerror2までコンソールに表示されます。

switchMapの場合、後から来たストリームに上書きはされることはあると思いますが、
処理が消滅する’（162行のmapが発火しない）ケースとして何か考えられますでしょうか。

（  .getTxsEvent().then().catch()ではエラーを取り切れないかと思い、
try catchの中に入れてみたりもしましたが、状況変わらずでした。。）

お手数おかけしますが、ご確認いただけますと幸いです。

2022-03-02 12:33 UTC, taro04 commented
複数回APIを叩く件、修正しました。
ローカルで動作確認し、以前のようにauthに切り替えてもbankの表示が残ったままだったり、ページ遷移したときにページが行ったり来たりすることはなくなったと思います。

以下修正の概要です。

![image](https://user-images.githubusercontent.com/75844498/156361157-76f9cb5c-8df5-4fcf-9681-7d4b052e3eb4.png)

・レビューで動かしていただけることもあるかと思いconsole.logは残しています。（マージできそうな段階で消します。）
・pageSizeと、pageNumberを個別に分けて、それぞれdistinctUntilChangedで変化したときだけ流すか迷いましたが、
　いったんコメントいただいた通りにオブジェクトにまとめて扱っています。

お手数ですが、ご確認お願いいたします。

2022-03-03 08:01 UTC, YasunoriMATSUOKA reviewed
@taro04 
色々検討してくださってありがとうございます！
負荷を下げるという観点、これでばっちりだと思います！
consoleや、コメントアウトの箇所、諸々消して頂く＆(これはついでという感じで恐縮ですが、)以前デバッグ用に一時的に書いて消し忘れていた`projects/main/src/app/pages/accounts/account/txs/txs.component.ts`の中のsubscribeや他にも同様のものがあったら消して頂けると助かります。
それでマージしましょう。
お手数ですが、最後、そこだけ、よろしくお願いします。

2022-03-03 11:43 UTC, taro04 commented
@YasunoriMATSUOKA 
確認ありがとうございます。

一晩おいてあらためて見て pageSize と pageNumberをpagenationInfoにまとめる必要ないと思いました。

Viewコンポーネントに渡す変数の中でこれだけオブジェクトにまとまっているのも違和感あったので、分ける方向で修正してもよいでしょうか。
（確認いただいたのにすみません。）

2022-03-03 11:49 UTC, YasunoriMATSUOKA commented
分けても通信回数同じなら分けてOKです

2022-03-03 12:23 UTC, taro04 commented
すみません。やはり実装してみると、まとめていないと成立しないことがわかりました。現状のままでいこうと思います。申し訳ありません。

（ combimeLatestにwithLatestFrom()をつなげられないので size、numberのどちらを変えても、txTotalCountの更新を経由しないで、txsだけを更新するためには、まとまっていることが必要でした。）

2022-03-03 12:47 UTC, taro04 commented
@YasunoriMATSUOKA 

・console削除しました。
・subscribeでプロジェクト検索し、明らかにデバック用と思われるものは削除しました。
　確認できる（proposal以外の）箇所は、削除の前後で動作におかしな点がないことを確認しました。

ご確認お願い致します。

2022-03-04 09:55 UTC, YasunoriMATSUOKA approved these changes
![LGTM](https://image.lgtmoon.dev/13874)

2022-03-04 10:05 UTC, merged