fix: deximals display
CauchyE/telescope pull request #299
Opened 2022-03-10 13:49 UTC by taro04

@YasunoriMATSUOKA 

小数点以下の表記を修正しました。
（フォント小さく、グレー）

[https://cauchye.slack.com/archives/CKV987JSW/p1646393621173669](https://cauchye.slack.com/archives/CKV987JSW/p1646393621173669)

例）homeページ
![20220310_fix](https://user-images.githubusercontent.com/75844498/157674376-d74ce750-72d0-487c-8eea-df121d5efb59.png)

angularのdecimal pipeで、小数点桁数を制限している箇所をプロジェクト検索し、自作のカスタムpipeで置き換えています。カスタムpipeのファイルを置く場所が正しいか併せて確認いただきたいです。

レビューお願いいたします。

2022-03-22 01:17 UTC, YasunoriMATSUOKA requested changes
@taro04 
コードレビューのみですが、実装方針はOKだと思います。
ただ、pipeは配置場所をpipesディレクトリ配下とかにまとめたほうが良いと思ったのでその点だけ修正お願いします。

2022-03-22 01:17 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/pipe.module.ts
> +export class PipeModule {}
配置場所、app直下ではなく、pipes等のディレクトリ作ってそこに配置がいいかなと思いました。

2022-03-22 01:17 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/cosmos/staking/validators/validator/validator.module.ts
> +import { PipeModule } from '../../../../pipe.module';
pipeの配置場所変わったら、import元も適宜変更してあげてください。

2022-03-22 01:17 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/accounts/account/staking/staking.module.ts
> +import { PipeModule } from '../../../pipe.module';
pipeの配置場所変わったら、import元も適宜変更してあげてください。

2022-03-22 01:17 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/accounts/account/distribution/distribution.module.ts
> +import { PipeModule } from '../../../pipe.module';
pipeの配置場所変わったら、import元も適宜変更してあげてください。

2022-03-22 01:20 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/pipe.module.ts
> +export class PipeModule {}
import元も必要あれば修正してあげてください。

2022-03-22 14:33 UTC, taro04 commented
@YasunoriMATSUOKA 

ファイル置く場所変更、コンフリクト解消実施しました。
utils側と合わせてレビューお願いいたします。

2022-03-22 14:35 UTC, taro04 commented on projects/main/src/app/views/pipe.module.ts
> +export class PipeModule {}
viewに置く必要はなかったです。
同pipesフォルダにpipesモジュールも追加してそれをインポートしています。

2022-03-25 09:21 UTC, YasunoriMATSUOKA approved these changes
![LGTM](https://image.lgtmoon.dev/98285)

2022-03-25 09:24 UTC, merged